CREATE TABLE TB_Sala (
    ID_SALA SERIAL PRIMARY KEY,
    NM_SALA VARCHAR(100) NOT NULL,
    TP_SALA VARCHAR(50),
    NU_CAPACIDADE INTEGER CHECK (NU_CAPACIDADE > 0)
);

CREATE TABLE TB_Equipamento (
    ID_EQUIPAMENTO SERIAL PRIMARY KEY,
    NM_EQUIPAMENTO VARCHAR(100) NOT NULL,
    TP_EQUIPAMENTO VARCHAR(50)
);

CREATE TABLE TB_Professor (
    ID_PROFESSOR SERIAL PRIMARY KEY,
    NM_PROFESSOR VARCHAR(100) NOT NULL,
    TP_AREA VARCHAR(100),
    ST_DISPONIBILIDADE BOOLEAN NOT NULL
);

CREATE TABLE TB_Disciplina (
    ID_DISCIPLINA SERIAL PRIMARY KEY,
    NM_DISCIPLINA VARCHAR(100) NOT NULL
);

CREATE TABLE TB_Turma (
    ID_TURMA SERIAL PRIMARY KEY,
    FK_DISCIPLINA INTEGER NOT NULL REFERENCES TB_Disciplina(ID_DISCIPLINA),
    FK_PROFESSOR INTEGER NOT NULL REFERENCES TB_Professor(ID_PROFESSOR),
    TP_PERIODO VARCHAR(10),
    ST_TURMA VARCHAR(20)
);

CREATE TABLE TB_Estudante (
    ID_ESTUDANTE SERIAL PRIMARY KEY,
    NM_ESTUDANTE VARCHAR(100) NOT NULL,
    CD_MATRICULA VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE TB_Horario (
    ID_HORARIO SERIAL PRIMARY KEY,
    TP_DIA_SEMANA VARCHAR(15) NOT NULL,
    DH_INICIO TIME NOT NULL,
    DH_FIM TIME NOT NULL
    CHECK (DH_FIM > DH_INICIO)
);

CREATE TABLE TB_Avaliacao (
    ID_AVALIACAO SERIAL PRIMARY KEY,
    FK_TURMA INTEGER NOT NULL REFERENCES TB_Turma(ID_TURMA),
    NM_AVALIACAO VARCHAR(100) NOT NULL,
    TP_AVALIACAO VARCHAR(50) NOT NULL,
    DT_AVALIACAO DATE NOT NULL,
    NU_PESO NUMERIC(4,2) NOT NULL CHECK (NU_PESO > 0)
);

CREATE TABLE RL_Sala_Equipamento (
    FK_SALA INTEGER REFERENCES TB_Sala(ID_SALA),
    FK_EQUIPAMENTO INTEGER REFERENCES TB_Equipamento(ID_EQUIPAMENTO),
    PRIMARY KEY (FK_SALA, FK_EQUIPAMENTO)
);

CREATE TABLE RL_Estudante_Turma (
    FK_ESTUDANTE INTEGER REFERENCES TB_Estudante(ID_ESTUDANTE),
    FK_TURMA INTEGER REFERENCES TB_Turma(ID_TURMA),
    PRIMARY KEY (FK_ESTUDANTE, FK_TURMA)
);

CREATE TABLE RL_Avaliacao_Estudante (
    FK_AVALIACAO INTEGER NOT NULL REFERENCES TB_Avaliacao(ID_AVALIACAO),
    FK_ESTUDANTE INTEGER NOT NULL REFERENCES TB_Estudante(ID_ESTUDANTE),
    NU_NOTA NUMERIC(5,2) CHECK (NU_NOTA BETWEEN 0 AND 10),
    PRIMARY KEY (FK_AVALIACAO, FK_ESTUDANTE)
);

CREATE TABLE RL_Alocacao (
    FK_TURMA INTEGER REFERENCES TB_Turma(ID_TURMA),
    FK_SALA INTEGER REFERENCES TB_Sala(ID_SALA),
    FK_HORARIO INTEGER REFERENCES TB_Horario(ID_HORARIO),
    PRIMARY KEY (FK_TURMA, FK_SALA, FK_HORARIO)
);

CREATE INDEX IDX_ESTUDANTE_TURMA ON RL_Estudante_Turma(FK_TURMA, FK_ESTUDANTE);
CREATE INDEX IDX_EQUIPAMENTO_SALA ON RL_Sala_Equipamento(FK_SALA, FK_EQUIPAMENTO);
CREATE INDEX IDX_NOTAS_AVALIACAO_TURMA ON RL_Avaliacao_Estudante(FK_AVALIACAO);


CREATE INDEX idx_estudante_nm ON TB_Estudante(nm_estudante);
CREATE INDEX idx_professor_nm ON TB_Professor(nm_professor);
CREATE INDEX idx_disciplina_nm ON TB_Disciplina(nm_disciplina);


CREATE INDEX idx_avaliacao_turma ON TB_Avaliacao(fk_turma);
CREATE INDEX idx_avaliacao_estudante_avaliacao ON RL_Avaliacao_Estudante(fk_avaliacao);
CREATE INDEX idx_avaliacao_estudante_estudante ON RL_Avaliacao_Estudante(fk_estudante);
CREATE INDEX idx_turma_professor ON TB_Turma(fk_professor);
CREATE INDEX idx_turma_disciplina ON TB_Turma(fk_disciplina);
CREATE INDEX idx_estudante_turma_estudante ON RL_Estudante_Turma(fk_estudante);
CREATE INDEX idx_estudante_turma_turma ON RL_Estudante_Turma(fk_turma);


CREATE INDEX idx_alocacao_turma ON RL_Alocacao(fk_turma);
CREATE INDEX idx_alocacao_sala ON RL_Alocacao(fk_sala);
CREATE INDEX idx_alocacao_horario ON RL_Alocacao(fk_horario);
