CREATE MATERIALIZED VIEW mv_disciplinas_laboratorios_sem_computador AS
SELECT
    d.NM_DISCIPLINA,
    s.NM_SALA,
    s.TP_SALA,
    e.NM_EQUIPAMENTO
FROM TB_Disciplina d
JOIN TB_Turma t ON d.ID_DISCIPLINA = t.FK_DISCIPLINA
JOIN RL_Alocacao a ON t.ID_TURMA = a.FK_TURMA
JOIN TB_Sala s ON a.FK_SALA = s.ID_SALA
LEFT JOIN RL_Sala_Equipamento se ON s.ID_SALA = se.FK_SALA
LEFT JOIN TB_Equipamento e ON se.FK_EQUIPAMENTO = e.ID_EQUIPAMENTO AND e.NM_EQUIPAMENTO = 'Computador'
WHERE s.TP_SALA = 'Laboratório' AND e.ID_EQUIPAMENTO IS NULL
GROUP BY d.NM_DISCIPLINA, s.NM_SALA, s.TP_SALA, e.NM_EQUIPAMENTO
ORDER BY s.NM_SALA;