CREATE MATERIALIZED VIEW mv_horarios_mais_utilizados AS
SELECT
    h.TP_DIA_SEMANA,
    h.DH_INICIO,
    h.DH_FIM,
    COUNT(*) AS QT_ALOCACOES,
    RANK() OVER (PARTITION BY h.TP_DIA_SEMANA ORDER BY COUNT(*) DESC) AS RANK_NO_DIA
FROM RL_Alocacao a
JOIN TB_Horario h ON a.FK_HORARIO = h.ID_HORARIO
GROUP BY h.TP_DIA_SEMANA, h.DH_INICIO, h.DH_FIM;
