CREATE MATERIALIZED VIEW mv_media_estudantes_por_turma AS
SELECT
    t.ID_TURMA,
    d.NM_DISCIPLINA,
    COUNT(et.FK_ESTUDANTE) AS QT_ESTUDANTES
FROM RL_Estudante_Turma et
JOIN TB_Turma t ON et.FK_TURMA = t.ID_TURMA
JOIN TB_Disciplina d ON t.FK_DISCIPLINA = d.ID_DISCIPLINA
GROUP BY t.ID_TURMA, d.NM_DISCIPLINA;
