CREATE MATERIALIZED VIEW mv_capacidade_por_tipo_sala_usada AS
SELECT
    s.TP_SALA,
    COUNT(DISTINCT s.ID_SALA) AS QT_SALAS_USADAS,
    ROUND(AVG(s.NU_CAPACIDADE), 2) AS MEDIA_CAPACIDADE,
    DENSE_RANK() OVER (ORDER BY AVG(s.NU_CAPACIDADE) DESC) AS POSICAO
FROM RL_Alocacao a
JOIN TB_Sala s ON a.FK_SALA = s.ID_SALA
JOIN TB_Horario h ON a.FK_HORARIO = h.ID_HORARIO
GROUP BY s.TP_SALA;
