CREATE MATERIALIZED VIEW mv_media_notas_por_disciplina AS
SELECT
    d.NM_DISCIPLINA,
    ROUND(AVG(r.NU_NOTA), 2) AS MEDIA_NOTA,
    COUNT(*) AS TOTAL_AVALIACOES,
    RANK() OVER (ORDER BY AVG(r.NU_NOTA) DESC) AS POSICAO
FROM RL_Avaliacao_Estudante r
JOIN TB_Avaliacao a ON r.FK_AVALIACAO = a.ID_AVALIACAO
JOIN TB_Turma t ON a.FK_TURMA = t.ID_TURMA
JOIN TB_Disciplina d ON t.FK_DISCIPLINA = d.ID_DISCIPLINA
GROUP BY d.NM_DISCIPLINA;
