CREATE MATERIALIZED VIEW mv_salas_ocupadas_hoje AS
SELECT
    s.NM_SALA,
    s.TP_SALA,
    h.TP_DIA_SEMANA,
    h.DH_INICIO,
    h.DH_FIM,
    COUNT(*) OVER (PARTITION BY h.TP_DIA_SEMANA, h.DH_INICIO) AS QT_OCUPACOES_MESMO_HORARIO
FROM RL_Alocacao a
JOIN TB_Sala s ON a.FK_SALA = s.ID_SALA
JOIN TB_Horario h ON a.FK_HORARIO = h.ID_HORARIO
WHERE h.TP_DIA_SEMANA = TO_CHAR(CURRENT_DATE, 'Day')
ORDER BY h.DH_INICIO;