CREATE MATERIALIZED VIEW mv_professor_turmas_e_notas AS
SELECT
    p.NM_PROFESSOR,
    COUNT(DISTINCT t.ID_TURMA) AS QT_TURMAS,
    ROUND(AVG(r.NU_NOTA), 2) AS MEDIA_NOTA_ALUNOS,
    RANK() OVER (ORDER BY COUNT(DISTINCT t.ID_TURMA) DESC) AS POSICAO_TURMAS
FROM TB_Professor p
JOIN TB_Turma t ON p.ID_PROFESSOR = t.FK_PROFESSOR
JOIN TB_Avaliacao a ON a.FK_TURMA = t.ID_TURMA
JOIN RL_Avaliacao_Estudante r ON r.FK_AVALIACAO = a.ID_AVALIACAO
GROUP BY p.NM_PROFESSOR;
