CREATE MATERIALIZED VIEW mv_avaliacoes_proximos_7_dias AS
SELECT
    d.NM_DISCIPLINA,
    a.NM_AVALIACAO,
    a.DT_AVALIACAO,
    COUNT(r.FK_ESTUDANTE) AS QT_ESTUDANTES_AVALIADOS
FROM TB_Avaliacao a
JOIN TB_Turma t ON a.FK_TURMA = t.ID_TURMA
JOIN TB_Disciplina d ON t.FK_DISCIPLINA = d.ID_DISCIPLINA
LEFT JOIN RL_Avaliacao_Estudante r ON r.FK_AVALIACAO = a.ID_AVALIACAO
WHERE a.DT_AVALIACAO BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '7 days'
GROUP BY d.NM_DISCIPLINA, a.NM_AVALIACAO, a.DT_AVALIACAO;
