CREATE MATERIALIZED VIEW mv_ranking_turmas_avaliacoes AS
SELECT
    t.ID_TURMA,
    d.NM_DISCIPLINA,
    COUNT(a.ID_AVALIACAO) AS QT_AVALIACOES,
    RANK() OVER (ORDER BY COUNT(a.ID_AVALIACAO) DESC) AS POSICAO
FROM TB_Turma t
JOIN TB_Disciplina d ON t.FK_DISCIPLINA = d.ID_DISCIPLINA
JOIN TB_Avaliacao a ON a.FK_TURMA = t.ID_TURMA
GROUP BY t.ID_TURMA, d.NM_DISCIPLINA;
